# Catalyst deployment — catalyst-ui

This is catalyst-ui's own instantiation of the catalyst framework.
Deployed via the greenfield path
(`development-framework/INSTANTIATION-GUIDE.md` §3, in the `catalyst`
repository): no application code existed yet, so the foundational
tooling, stack, and dev-environment decisions were established as this
deployment's first rule document before any product code was written.

## Structure

```
CODE-OF-CONDUCT.md      Dev-artifact standards, users/roles, slash commands (from
                         development-framework/rules-of-development.template.md)
rules/
  Rules-of-Rules.md      Meta-rules governing this deployment's rules
  rules.md                Global rule index
  dev-environment-rules.md   Tooling/process rules (prefix `env`) — the
                              only rule document today
  domains/                RUNTIME, LAYOUT, DEPS, STYLE, TEST, CI, DX
requirements/            REQ- docs (none yet)
features/                FEAT- entries (none yet)
reconciliations/         RECON- cases (none yet)
IAM/
  users/users.json        One registered user (Olivier Steck, Admin)
  roles/roles.json         Default agile-role mapping
development/
  bugs/, house-keeping/, meta-tags/   (none yet)
  BACKLOG.md              Regenerated by /show-backlog — never hand-edited
  roadmaps/                Named roadmaps (none yet — add one via /roadmap-add)
  journal.jsonl             Append-only, transaction-log-grade change history —
                             see rules/Rules-of-Rules.md §12
version.txt               0.17.0 — the framework version this was deployed against
```

`work-items/` is not part of this deployment — plugin-territory, not
core (INV-22); no project-management plugin is active.

## Why greenfield, not retrofit

No catalyst-ui code existed anywhere before this instantiation. The
mirror-image retrofit path extracts rules from existing practice;
greenfield establishes practice as rules first. See
`rules/dev-environment-rules.md` for what got decided (Node 20 LTS,
TypeScript strict, npm workspaces, ESLint+Prettier, Vitest/Mocha,
GitHub Actions CI) and verified working against the still-empty
scaffold before this deployment was considered done.

## Current state

- One rule document (`dev-environment-rules.md`), 7 domains, 7 rules —
  all ✅, each with a real config file in the repository and a verified
  clean tool/CI run.
- One registered user (`IAM/users/users.json`), satisfying the hard "at
  least one active user" requirement.
- No bugs, requirements, features, reconciliations, or roadmaps yet —
  this deployment installs the skeleton and the dev-environment rules;
  product rules and requirements come once real application work
  starts (`INSTANTIATION-GUIDE.md` §3 step 5).

## Commit status

Nothing in `/Users/oliviersteck/sources/catalyst-ui` has been committed
or pushed yet (`INVARIANTS.md` INV-4) — review it, then explicitly say
so if you want it committed.
