# Catalyst deployment — catalyst-ui

This is catalyst-ui's own instantiation of the catalyst framework.
Deployed via the greenfield path
(`framework/kernel/INSTANTIATION-GUIDE.md` §3, in the `catalyst`
repository): no application code existed yet, so the foundational
tooling, stack, and dev-environment decisions were established as this
deployment's first rule document before any product code was written.

## Structure

This working copy is the `.criterion` submodule of catalyst-ui, shared
through `catalyst-ui-criterion` (branch `criterion`); changes land by
`catalyst criterion push` pull requests. Versions (kernel, module) and the
sync history are in [`DEPLOYMENT.md`](DEPLOYMENT.md), not repeated here.

```text
CODE-OF-CONDUCT.md      Dev-artifact standards, users/roles, slash commands (the
                         kernel's rules-of-development.template.md composed
                         with the active module's code-of-conduct.module.md)
ACCESS-CONTROL.md       Per-role read/write rights reference (from the kernel)
ANALYSIS-PLAYBOOK.md    The four-eyes analysis process run by /run-analysis
DEPLOYMENT.md           Project, kernel, module, and the sync history
Taskfile.common.yml     Thin task dispatch per CODE-OF-CONDUCT.md §4 command,
                         included by catalyst-ui's root Taskfile.yml
bin/catalyst.pyz        The vendored catalyst CLI
modules/
  software-engineering/   The active process module, whole release tree
rules/
  Rules-of-Rules.md      Meta-rules governing this deployment's rules
  rules.md                Global rule index
  dev-environment-rules.md   Tooling/process rules (prefix `env`)
  catalyst-core-rules.md     `packages/catalyst-core` contract rules (prefix `core`)
  catalyst-host-vscode-rules.md  VS Code host rules (prefix `vscode`)
  catalyst-host-electron-rules.md  Electron host rules (prefix `electron`)
  domains/                One file per DOMAIN across the rule documents
requirements/            REQ- docs
features/                FEAT- entries
steps/                   STEP- implementation-work records
tests/                   TEST- verification artifacts
analyses/                ANALYSIS- records of four-eyes code analyses, with
                         their reports in analyses/reports/<ID>/
proposals/               Proposal-loop artifacts (deployment-local type)
runs/                    Agent run-state artifacts (deployment-local type)
reconciliations/         RECON- cases
workflows/               WORKFLOW- process-definition docs
definitions/             One frozen prose definition per entity type
IAM/
  users/users.json        Registered users
  roles/roles.json        Roles, each with a `reconciliation` gate
                           (full/propose/none)
development/
  bugs/, house-keeping/, meta-tags/
  BACKLOG.md              Regenerated by /show-backlog — never hand-edited
  roadmaps/               Named roadmaps
  journal.jsonl           Append-only change history (rules/Rules-of-Rules.md §12)
version.txt               The kernel version this was last synced against
```

`work-items/` is not part of this deployment — plugin-territory, not
core (INV-22); no project-management plugin is active.

## Discoverability

- [`CODE-OF-CONDUCT.md`](CODE-OF-CONDUCT.md) — dev-artifact standards,
  users/roles, and every slash command's full spec (§4).
- [`ACCESS-CONTROL.md`](ACCESS-CONTROL.md) — per-role read/write rights
  and when the agent may auto-sign a write.
- [`rules/Rules-of-Rules.md`](rules/Rules-of-Rules.md) — meta-rules
  governing the rules themselves.

## Why greenfield, not retrofit

No catalyst-ui code existed anywhere before this instantiation. The
mirror-image retrofit path extracts rules from existing practice;
greenfield establishes practice as rules first. See
`rules/dev-environment-rules.md` for what got decided (Node 20 LTS,
TypeScript strict, npm workspaces, ESLint+Prettier, Vitest/Mocha,
GitHub Actions CI) and verified working against the still-empty
scaffold before this deployment was considered done.

## Current state

- Four rule documents (`env`, `core`, `vscode`, `electron`), 20 domains,
  20 rules — all ✅ working, each with a real config/implementation file
  in the repository and a verified clean tool/CI run.
- Nine requirements and nine features, tracking the roadmap's phases
  1–7 plus two phases added beyond the original pasted roadmap
  (multi-root workspace support, the agent window for slash commands).
- One registered user (`IAM/users/users.json`), satisfying the hard "at
  least one active user" requirement.
- No bugs, house-keeping items, reconciliations, or workflows yet.

## Commit status

Nothing in `/Users/oliviersteck/sources/catalyst-ui` has been committed
or pushed yet (`INVARIANTS.md` INV-4) — review it, then explicitly say
so if you want it committed.
